server:
  port: 8080

jwt:
  secret: 4hcv7876v435nc8720ufh3nbwq0c94232h2fu03
  lifetime: 1440m

user-with-activation-code:
  lifetime: 20m

upload:
  path: "C:\\Users\\igorl\\IdeaProjects\\moviesbackend\\users_avatars"

server-address:
  url: http://localhost:8080

client-address:
  url: http://localhost:3000



#  spring.http.multipart.max-file-size=10MB
#  spring.http.multipart.max-request-size=11MB


spring:

  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/my_db?useSSL=false&amp
    url: jdbc:mysql://localhost:3306/my_db?user=root
    username: root
    password: bestuser

  mail:
    host: smtp.gmail.com
    port: 587
    username: igorlov18@gmail.com
    password: "vvoy dwvj rhqd qhmf"
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


    sender:
      email: movies-rezka@gmail.com
      text: no-reply
  web:
    resources:
      static-locations: file:\D:\myProjectsCopy\media\movies
  mvc:
    static-path-pattern: /image/**






